version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:8080"  # Changed from 5000 to 3000 to avoid port conflict
    volumes:
      - ./SWIGGY:/app/SWIGGY  # Mount SWIGGY folder for shared access
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  # Vite dev server port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge